### ISSUE TITLE
feature：update app first

### ISSUE THREAD

**Issue by ivysrono** [stirante/StorePrefs#1]
Just like：
Market Update Helper
https://play.google.com/store/apps/details?id=com.keramidas.MarketUpdateHelper

**Comment by stirante** [comment]
Umm, on playstore in screens i have 2 black rectangles and literally no description what it does. Could you tell me exactly what you want me to add?

**Comment by ivysrono** [comment]
Google push update batch after bactch，so I want to get the update at the first time.
